import {
  ACCOUNT_ID,
  API_URL,
  GRAPHQL_ENDPOINT,
  IDENTITY_POOL_ID,
  MEDIA_DRIVE_CDN,
  POOL_DATA,
  REGION,
  UPLOAD_BUCKET_NAME,
  FLIGHTS_CDN
} from "./env.js";
import {PASSWORD, USER_NAME} from "./user.js";
import {FOLDER_ID} from "./media-config.js";

export {
  FOLDER_ID,
  USER_NAME,
  PASSWORD,
  GRAPHQL_ENDPOINT,
  ACCOUNT_ID,
  IDENTITY_POOL_ID,
  POOL_DATA,
  MEDIA_DRIVE_CDN,
  UPLOAD_BUCKET_NAME,
  REGION,
  API_URL,
  FLIGHTS_CDN
};
